name: CI

on: [push]

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@master

      - name: Install Rust stable
        run: |
          rustup toolchain update --no-self-update stable
          rustup default stable
          rustup component add clippy rustfmt

      - name: Run rustfmt
        run: cargo fmt -- --check

      - name: Run clippy
        run: cargo clippy --all --all-features
        # when the typemap stuff gets resolved
        # run: cargo clippy --all --all-features -- -Dwarnings

  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        rust_versions: ["stable", "1.38.0"]
        os: [ubuntu-latest, windows-latest]
        cargo_build_flags: ["--all-features"]
    steps:
      - name: Checkout the source code
        uses: actions/checkout@master

      - name: Install Rust Versions
        run: |
          rustup toolchain install --no-self-update ${{ matrix.rust_versions }}
          rustup default stable

      - name: Build lib
        run: rustup run ${{ matrix.rust_versions }} cargo build ${{ matrix.cargo_build_flags }}

      - name: Test lib
        run: cargo test ${{ matrix.cargo_build_flags }} -- ${{ matrix.test_flags }}

  features:
    name: Test Individual Features
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@master

      - name: Install Rust toolchain and jq
        run: |
          rustup toolchain install --no-self-update stable
          rustup default stable
          apt-get update
          apt-get install -y --no-install-recommends jq

      - name: Test lib
        run: |
          for feature in $(cargo read-manifest | jq -r '.features|keys|join("\n")'); do
            echo building with feature "$feature"
            cargo test --no-default-features --features "$feature"
          done
